### PR TITLE
improved WPI install and check methods.

### PR DESCRIPTION
**Pull request by RSabounds**

### CODE REVIEW

**Comment by jonathan-madison** [comment]
Alan, thanks for opening an issue. I have added you to the repo as a collaborator so you can update the issue now.

Can you elaborate on this so we know what's going on?

**Comment by RSabounds** [comment]
Thanks, I'll work on a write-up of changed elements and update.

**Comment by RSabounds** [comment]
This update re-writes the method of testing install status, and the method for install itself.
reason: Installation tests with requirement for elements requiring more than 1 unique element automatically included by WPI would hang at 30 seconds and not complete install. Also, test validation was failing for some modules even after successful installation.
edits: Changing the method used for the call utilized allowed for smoother run of installation process with no 'timeout' variable required. Testing was also set to a dual method:
1) .NET call to WPI framework to ensure installed status = true.
2) backup test to CMD to validate utility is installed.
In some cases, the CMD call would not enumerate correctly, due to cmd-line cropping. The .NET call was more effective in tests.
I also added a variable option, as some configurations allow for 'additional arguments', such as SQL express, etc.

**Comment by RSabounds** [comment]
retracting and testing push to local repo. will re-publish when files are pushing proper non-binary.

**Pull request closed without merging**
